# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/cloudsecurity.UserService/login',
                request_serializer=cloudsecurity__pb2.Request.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.Enroll = channel.unary_unary(
                '/cloudsecurity.UserService/Enroll',
                request_serializer=cloudsecurity__pb2.EnrollRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.VerifyOTP = channel.unary_unary(
                '/cloudsecurity.UserService/VerifyOTP',
                request_serializer=cloudsecurity__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.AddNode = channel.unary_unary(
                '/cloudsecurity.UserService/AddNode',
                request_serializer=cloudsecurity__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.ConnectNodes = channel.unary_unary(
                '/cloudsecurity.UserService/ConnectNodes',
                request_serializer=cloudsecurity__pb2.ConnectNodesRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.InitiateFileTransfer = channel.unary_unary(
                '/cloudsecurity.UserService/InitiateFileTransfer',
                request_serializer=cloudsecurity__pb2.FileTransferRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.ProcessFileTransfer = channel.unary_unary(
                '/cloudsecurity.UserService/ProcessFileTransfer',
                request_serializer=cloudsecurity__pb2.ProcessTransferRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.GetNetworkStats = channel.unary_unary(
                '/cloudsecurity.UserService/GetNetworkStats',
                request_serializer=cloudsecurity__pb2.Empty.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateFileTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFileTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=cloudsecurity__pb2.Request.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=cloudsecurity__pb2.EnrollRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=cloudsecurity__pb2.VerifyOTPRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=cloudsecurity__pb2.AddNodeRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'ConnectNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectNodes,
                    request_deserializer=cloudsecurity__pb2.ConnectNodesRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'InitiateFileTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateFileTransfer,
                    request_deserializer=cloudsecurity__pb2.FileTransferRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'ProcessFileTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFileTransfer,
                    request_deserializer=cloudsecurity__pb2.ProcessTransferRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'GetNetworkStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkStats,
                    request_deserializer=cloudsecurity__pb2.Empty.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudsecurity.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudsecurity.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/login',
            cloudsecurity__pb2.Request.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/Enroll',
            cloudsecurity__pb2.EnrollRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/VerifyOTP',
            cloudsecurity__pb2.VerifyOTPRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/AddNode',
            cloudsecurity__pb2.AddNodeRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/ConnectNodes',
            cloudsecurity__pb2.ConnectNodesRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateFileTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/InitiateFileTransfer',
            cloudsecurity__pb2.FileTransferRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFileTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/ProcessFileTransfer',
            cloudsecurity__pb2.ProcessTransferRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworkStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudsecurity.UserService/GetNetworkStats',
            cloudsecurity__pb2.Empty.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
        def fname(arg):
                pass